version: '3'
services:
  db:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=dbentrada
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=''
      - DB_NAME=dbentrada
      - DB_PORT=3306
    volumes:
      - ./backend/dbentrada.sql:/docker-entrypoint-initdb.d/dbentrada.sql
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data:
