version: '3.7'

services:

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=''
      - MYSQL_DB=dbentrada
    volumes:
      - ./backend/dbentrada.sql:/docker-entrypoint-initdb.d/dbentrada.sql
    depends_on:
      - db
      - migration
    command: sh -c "sleep 20 && npm start"

  frontend:
    build:
      context: frontend/dist/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
      - migration

  db:
    image: mysql:8.0.33
    container_name: db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=dbentrada
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80
  
  migration:
    build:
      context: backend/
      dockerfile: Dockerfile
    depends_on:
      - db
    command: sh -c "sleep 10 && npx sequelize-cli db:migrate && npx sequelize db:seed:all"

volumes:
  mysql-data:
