version: '3.7'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - 3000:3000
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=''
      - MYSQL_DB=dbentrada
    volumes:
      - ./backend/dbentrada.sql:/docker-entrypoint-initdb.d/dbentrada.sql
    depends_on:
      - db
      - migration
    networks:
      - app-network
    command: sh -c "sleep 70 && npm start"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - 80:4200
    depends_on:
      - db
      - migration
    networks:
      - app-network
    command: sh -c "sleep 70 && npm start"

  db:
    image: mysql:8.0.33
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=dbentrada
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  migration:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    depends_on:
      - db
    networks:
      - app-network
    command: sh -c "sleep 60 && npx sequelize-cli db:migrate && npx sequelize db:seed:all"

networks:
  app-network:

volumes:
  mysql-data:
