version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=''
      - MYSQL_DB=dbentrada
    volumes:
      - ./backend/dbentrada.sql:/docker-entrypoint-initdb.d/dbentrada.sql
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0.33
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=dbentrada
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - app
    networks:
      - app-network
    command: sh -c "sleep 100 && npx sequelize-cli db:migrate"

networks:
  app-network:

volumes:
  mysql-data:
